# Generated by Django 3.0.4 on 2020-03-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tracker', '0003_auto_20200306_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Attendant',
            name='in_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='Attendant',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
